export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      brewery_profiles: { Row: { id: string; name: string; legal_name: string | null; display_name: string | null; country: string | null; timezone: string; currency: string; language: string; vat_number: string | null; excise_authorization_number: string | null; is_small_independent_brewery: boolean; emcs_enabled: boolean; packaging_contribution_mode: string | null; onboarding_status: string; created_at: string; updated_at: string }; Insert: Omit<Database['public']['Tables']['brewery_profiles']['Row'],'id'|'created_at'|'updated_at'> & { id?: string; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['brewery_profiles']['Insert']> }; 
      ingredients: { Row: { id: string; brewery_id: string; name: string; category: string | null; ingredient_type: string; default_unit: string | null; is_active: boolean; created_at: string; updated_at: string }; Insert: Omit<Database['public']['Tables']['ingredients']['Row'],'id'|'created_at'|'updated_at'> & { id?: string; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['ingredients']['Insert']> };
      packaging_formats: { Row: { id: string; brewery_id: string; name: string; container_type: string; package_size_label: string | null; size_liters: number; is_reusable: boolean; packaging_contribution_category: string | null; is_active: boolean; notes: string | null; created_at: string; updated_at: string }; Insert: Omit<Database['public']['Tables']['packaging_formats']['Row'],'id'|'created_at'|'updated_at'> & { id?: string; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['packaging_formats']['Insert']> };
      recipes: { Row: { id: string; brewery_id: string; name: string; default_batch_size_liters: number | null; target_og: number | null; target_fg: number | null; target_pre_boil_volume_liters: number | null; target_post_boil_volume_liters: number | null; target_fermenter_volume_liters: number | null; default_boil_duration_min: number | null; default_yeast_notes: string | null; default_packaging_type: string | null; default_packaging_format_id: string | null; is_active: boolean; notes: string | null; created_at: string; updated_at: string }; Insert: Omit<Database['public']['Tables']['recipes']['Row'],'id'|'created_at'|'updated_at'> & { id?: string; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['recipes']['Insert']> };
      batches: { Row: { id: string; brewery_id: string; batch_number: string | null; declaration_number: string | null; recipe_id: string | null; brew_date: string | null; status: string; target_volume_liters: number | null; actual_volume_liters: number | null; notes: string | null; created_at: string; updated_at: string }; Insert: Omit<Database['public']['Tables']['batches']['Row'],'id'|'created_at'|'updated_at'> & { id?: string; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['batches']['Insert']> };
      brew_logs: { Row: { id: string; brewery_id: string; batch_id: string; brew_date: string | null; actual_mash_volume_liters: number | null; actual_strike_water_temp_c: number | null; actual_pre_boil_volume_liters: number | null; actual_post_boil_volume_liters: number | null; actual_boil_duration_min: number | null; actual_fermenter_volume_liters: number | null; yeast_pitch_temp_c: number | null; yeast_notes: string | null; packaged_date: string | null; packaged_volume_liters: number | null; packaging_format_id: string | null; exceptions: string | null; brewer_notes: string | null; log_status: string; created_at: string; updated_at: string }; Insert: Omit<Database['public']['Tables']['brew_logs']['Row'],'id'|'created_at'|'updated_at'> & { id?: string; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['brew_logs']['Insert']> };
      lots: { Row: { id: string; brewery_id: string; batch_id: string | null; parent_lot_id: string | null; packaging_format_id: string | null; lot_number: string; internal_lot_ref: string | null; lot_type: string; status: string; packaging_state: string; excise_state: string; volume_liters: number | null; units_count: number | null; lot_date: string | null; notes: string | null; created_at: string; updated_at: string }; Insert: Omit<Database['public']['Tables']['lots']['Row'],'id'|'created_at'|'updated_at'> & { id?: string; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['lots']['Insert']> };
      sales: { Row: { id: string; brewery_id: string; lot_id: string | null; customer: string; sale_date: string | null; volume_sold: number | null; unit: string | null; invoice_number: string | null; status: string; due_date: string | null; amount: number | null; currency: string; excise_mode: string | null; arc_reference: string | null; emcs_reference: string | null; stock_direction: string; elimination_reason: string | null; notes: string | null; created_at: string; updated_at: string }; Insert: Omit<Database['public']['Tables']['sales']['Row'],'id'|'created_at'|'updated_at'> & { id?: string; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['sales']['Insert']> };
      declarations: { Row: { id: string; brewery_id: string; declaration_number: string | null; declaration_type: string; period_start: string; period_end: string; submission_date: string | null; status: string; reference_number: string | null; notes: string | null; created_at: string; updated_at: string }; Insert: Omit<Database['public']['Tables']['declarations']['Row'],'id'|'created_at'|'updated_at'> & { id?: string; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['declarations']['Insert']> };
      inventory_movements: { Row: { id: string; brewery_id: string; movement_timestamp: string; movement_type: string; scope: string | null; ingredient_id: string | null; ingredient_receipt_id: string | null; lot_id: string | null; source_lot_id: string | null; destination_lot_id: string | null; batch_id: string | null; sale_id: string | null; quantity: number; unit: string; base_quantity_liters: number | null; base_quantity_kg: number | null; direction: string; excise_effect: boolean; reference_number: string | null; reason: string | null; notes: string | null; source_pending_movement_id: string | null; elimination_reason: string | null; created_at: string }; Insert: Omit<Database['public']['Tables']['inventory_movements']['Row'],'id'|'created_at'> & { id?: string; created_at?: string }; Update: Partial<Database['public']['Tables']['inventory_movements']['Insert']> };
      pending_movements: { Row: { id: string; brewery_id: string; pending_type: string; scope: string | null; ingredient_id: string | null; ingredient_receipt_id: string | null; batch_id: string | null; lot_id: string | null; source_lot_id: string | null; destination_lot_id: string | null; sale_id: string | null; quantity: number | null; unit: string | null; direction: string | null; missing_fields_summary: string | null; why_completion_matters: string | null; resolution_status: string; completion_notes: string | null; elimination_reason: string | null; linked_task_id: string | null; created_at: string; updated_at: string }; Insert: Omit<Database['public']['Tables']['pending_movements']['Row'],'id'|'created_at'|'updated_at'> & { id?: string; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['pending_movements']['Insert']> };
      event_logs: { Row: { id: string; brewery_id: string; actor_user_id: string | null; actor_role: string | null; event_type: string; object_type: string | null; object_id: string | null; related_ids: Record<string, unknown> | null; event_timestamp: string; summary: string | null; payload_json: Record<string, unknown> | null; created_at: string }; Insert: Omit<Database['public']['Tables']['event_logs']['Row'],'id'|'created_at'|'event_timestamp'> & { id?: string; created_at?: string; event_timestamp?: string }; Update: Partial<Database['public']['Tables']['event_logs']['Insert']> };
    };
  };
}
